/**
 * Optional localized display name overrides for models.
 *
 * Keyed by normalized model id (use forward slashes for paths).
 * Example:
 * {
 *   'CHA_Alf_SSR_01': { en: 'Alf', kr: '알프' },
 *   'StellarSora/assets/.../10301_L': { en: 'Unit 10301 L', kr: '10301 L' },
 * }
 */
export const ModelNameOverrides: Record<string, Record<string, string>> = {
  // Add overrides here as needed.
  'CHA_Bibi_NPC_01': { zh: '小哔', en: 'Beepy' },
  'CHA_Bibi_NPC_02': { zh: '小哔原型', en: 'Beepy Prototype' },
  'CHA_Bibi_NPC_03': { zh: '小哔丹德莱', en: 'Dandegate' },
  'greencat': { zh: '格琳喵', en: 'Kalinyan' },
  'CHA_Berser_NPC_01': { zh: '布瑟尔', en: 'Berserl' },
  'CHA_Inspector_NPC_01': { zh: '检察员', en: 'Inspector' },
  'CHA_Lieutenant_NPC_01': { zh: '驻军中尉', en: 'Garrison Lieutenant' },
  'CHA_Consignor_NPC_01': { zh: '委托人', en: 'Client' },
  'CHA_Ussery_NPC_01': { zh: '厄舍上尉', en: 'Captain Ussery' },
  'CHA_Vladimir_NPC_01': { zh: '弗拉基米尔准尉', en: 'Warrant Officer Vladimir' },
  'CHA_Unitas_NPC_01': { zh: '帕拉蒂斯徒从', en: 'Paradeus Follower' },
  'CHA_Unitas_NPC_02': { zh: '年轻帕拉蒂斯徒从', en: 'Paradeus Follower Young' },
  'CHA_Crifium_NPC_01': { zh: '赫瑞尤', en: 'Crifium' },
  'CHA_RNDmale_NPC_01': { zh: '男性路人', en: 'Male Passerby' },
  'CHA_RNDmale_NPC_02': { zh: '男性路人戴帽子', en: 'Male Passerby Hat' },
  'CHA_Farkas_NPC_01': { zh: '佛尔卡什', en: 'Farkas' },
  'CHA_Flagg_NPC_01': { zh: '弗拉格', en: 'Flagg' },
  'CHA_Dmitriy_NPC_01': { zh: '德米特里年长', en: 'Dmitry' },
  'CHA_Dmitriy_Young_NPC': { zh: '德米特里年轻', en: 'Dmitry Young' },
  'CHA_Soldier01_NPC_01': { zh: '勘测部队士兵A', en: 'Survey Corps Soldier A' },
  'CHA_Soldier01_NPC_02': { zh: '勘测部队士兵B', en: 'Survey Corps Soldier B' },
  'CHA_Liaison_NPC_01': { zh: '勘测部队联络员', en: 'Survey Corps Liaison Officer' },
  'CHA_Loring_NPC_01': { zh: '洛林', en: 'Larion' },
  'CHA_Ivan_NPC_01': { zh: '伊万', en: 'Ivan' },
  'CHA_Deele_NPC_01': { zh: '德尔', en: 'Dier' },
  'CHA_Nikolay_NPC_01': { zh: '尼古拉', en: 'Nikolai' },
  'CHA_MysteryMan_NPC_01': { zh: '神秘人', en: 'Mysterious Man' },
  'CHA_MangiEmployee_NPC_01': { zh: '曼尼安保成员', en: 'Mangi Security Member' },
  'CHA_Bowen_NPC_01': { zh: '波文', en: 'Bowen' },
  'CHA_AnshangQ_NPC_01': { zh: '雅各布', en: 'Jakub' },
  'CHA_CensorLeo_NPC_01': { zh: '监察官雷欧', en: 'Inspector Leo' },
  'CHA_CaptainKellen_NPC_01': { zh: '远征队长凯伦', en: 'Expedition Leader Garen' },
  'CHA_MangiKnellA_NPC_01': { zh: '噩兆小队A', en: 'Omen Squad A' },
  'CHA_MangiKnellB_NPC_01': { zh: '噩兆小队B', en: 'Omen Squad B' },
  'CHA_MangiKnellC_NPC_01': { zh: '噩兆小队C', en: 'Omen Squad C' },
  'CHA_MangiKnellD_NPC_01': { zh: '噩兆小队D', en: 'Omen Squad D' },
  'CHA_Davey_NPC_01': { zh: '戴维', en: 'David' },
  'CHA_Green_RichMale01_NPC_01': { zh: '白区男性', en: 'White Zone Man' },
  'CHA_Green_NormalMale01_NPC_01': { zh: '绿区男性', en: 'Green Zone Man' },
  'CHA_Yellow_NormalMale01_NPC_01': { zh: '黄区男性', en: 'Yellow Zone Man' },
  'CHA_Fadei_NPC_01': { zh: '斐狄', en: 'Fedya' },
  'CHA_Rurik_NPC_01': { zh: '留里克', en: 'Rurik' },
  'CHA_Zimmermann_NPC_01': { zh: '齐默尔曼', en: 'Zimmerman' },
  'CHA_Zimmermann_NPC_02': { zh: '齐默尔曼（里）', en: 'Zimmerman（里）' },
  'CHA_Pavel_NPC_01': { zh: '巴维尔', en: 'Pavel（巴维尔）' },
  'CHA_Karl_NPC_01': { zh: '卡尔', en: 'Karl' },
  'CHA_Yakov_NPC_01': { zh: '雅科夫', en: 'Yakov' },
  'CHA_Lonnie_NPC_01': { zh: '朗尼', en: 'Lonnie' },
  'CHA_URNCofficer_NPC_01': { zh: '军方代表', en: 'URNC Officer' },
  'CHA_Kryuger_NPC_01': { zh: '克鲁格', en: 'Kryuger' },
  'CHA_6P62_BOSS_01': { zh: '6P62BOSS', en: '6P62 Boss' },
  'CHA_6P62_xinyuanguaidao_01': { zh: '6P62怪盗', en: '6P62 Phantom Thief' },
  'CHA_Griffin_NPC_01': { zh: '爵士', en: 'Earl' },
  'CHA_Havier_NPC_01': { zh: '哈维尔', en: 'Havier' },
  'CHA_Olek_NPC_01': { zh: '奥列克', en: 'Olek' },
  'CHA_Konny_NPC_01': { zh: '柯尼', en: 'Kenny' },
  'CHA_MaleCouriers_NPC_01': { zh: '配送员B', en: 'Deliveryman B' },
  'CHA_predecessor_NPC_01': { zh: '货车前辈', en: 'Truck-senpai' },
  'CHA_EngineerA_NPC_01': { zh: '白怀德', en: 'Bai Huaide' },
  'CHA_ManagerB_NPC_01': { zh: '乔治', en: 'George' },
  'CHA_ManagerB_NPC_02': { zh: '乔治年轻', en: 'George Young' },
  'CHA_FacilitatorC_NPC_02': { zh: '瓦西尔监禁', en: 'Vasil Imprisoned' },
  'CHA_FacilitatorC_NPC_01': { zh: '瓦西尔', en: 'Vasil' },
  'CHA_FacilitatorC_NPC_03': { zh: '瓦西尔年轻', en: 'Vasil Young' },
  'CHA_CaptainKellen_NPC_02': { zh: '莫科什誓卫军D', en: 'Mokosh Guard D' },
  'CHA_CaptainKellen_NPC_03': { zh: '莫科什誓卫军E', en: 'Mokosh Guard E' },
  'CHA_CaptainKellen_NPC_04': { zh: '莫科什誓卫军F', en: 'Mokosh Guard F' },
  'CHA_NobleGuardian_01': { zh: '财团人形', en: 'Conglomerate Doll' },
  'CHA_Yellow_GuardMale_01': { zh: '卫队成员男', en: 'Guard Member Male' },
  'CHA_Pavel_01': { zh: '帕维尔', en: 'Pavel（帕维尔）' },
  'CHA_Pegaso_01': { zh: '珀伽索', en: 'Pegasus' },
  'CHA_Poludnitsa_NPC_01': { zh: '佩妮泽', en: 'Poludnitsa' },
  'CHA_Nemesis_R_01': { zh: '纳美西丝R', en: 'Nemesis R' },
  'CHA_Nemesis_SR_01': { zh: '纳美西丝SR', en: 'Nemesis SR' },
  'CHA_Nemesis_Rest_01': { zh: '纳美西丝Rest', en: 'Nemesis Rest' },
  'CHA_Nemesis_Paradeus_01': { zh: '纳美西丝Paradeus', en: 'Nemesis Paradeus' },
  'CHA_Peritya_SSR_01': { zh: '佩里缇亚SSR', en: 'Peritya SSR' },
  'CHA_Saga_NPC_01': { zh: '萨珈', en: 'Saga' },
  'CHA_Helianthus_NPC_01': { zh: '赫丽安图丝', en: 'Helianthus' },
  'CHA_Daiyan_SSR_01': { zh: '黛烟SSR', en: 'Daiyan SSR' },
  'CHA_Lind_SSR_01': { zh: '琳德SSR', en: 'Lind SSR' },
  'CHA_Mosinnagant_SSR_01': { zh: '莫辛纳甘SSR', en: 'Mosin-Nagant SSR' },
  'CHA_Springfield_NPC_01': { zh: '春田咖啡馆', en: 'Springfield Café' },
  'CHA_Ullrid_SSR_01': { zh: '乌尔丽德SSR', en: 'Ullrid SSR' },
  'CHA_Ullrid_Mask_01': { zh: '乌尔丽德面具', en: 'Ullrid Mask' },
  'CHA_Lampetia_NPC_01': { zh: '兰珀蒂娅', en: 'Lambertia' },
  'CHA_Blusphere_NPC_01': { zh: '蓝雪球', en: 'Blusphere' },
  'CHA_Blusphere_NPC_02': { zh: '蓝雪球战损', en: 'Blusphere Damaged' },
  'CHA_Drachen_NPC_01': { zh: '德拉臣', en: 'Drachen' },
  'CHA_Springfield_NPC_SP': { zh: '春田少1', en: 'Springfield GF1' },
  'CHA_Springfield_SSR_01': { zh: '春田SSR', en: 'Springfield SSR' },
  'CHA_Lenten_NPC_01': { zh: '兰汀', en: 'Lentine' },
  'CHA_Lenten_NPC_02': { zh: '兰汀一代', en: 'Lentine Past' },
  'CHA_Carmen_NPC_01': { zh: '卡门', en: 'Carmen' },
  'CHA_Inessa_NPC_01': { zh: '伊涅萨', en: 'Inesa' },
  'CHA_Cocoon_NPC_01': { zh: '茧', en: 'Cocoon' },
  'CHA_Seele_NPC_01': { zh: '希尔', en: 'Sier' },
  'CHA_Orphina_NPC_01': { zh: '奥尔菲娅', en: 'Orphia' },
  'CHA_Isha_NPC_01': { zh: '伊莎', en: 'Isa' },
  'CHA_Voymastina_SSR_01': { zh: '威玛西娜SSR', en: 'Voymastina SSR' },
  'CHA_Acicular_NPC_01': { zh: '针', en: 'Igla' },
  'CHA_Acicular_Meta_01': { zh: '针兵器', en: 'Igla Weapon' },
  'CHA_Voymastina_SSR_02': { zh: '威玛西娜机甲', en: 'Voymastina Mech' },
  'CHA_Helen_SSR_01': { zh: '海伦SSR', en: 'Helen SSR' },
  'CHA_Helen_Suit_01': { zh: '海伦一代', en: 'Helen Past' },
  'CHA_Helen_SSR_02': { zh: '海伦礼服', en: 'Helen Dress' },
  'CHA_Helen_Suit_02': { zh: '海伦曼尼安保', en: 'Helen Mangi Security' },
  'CHA_Helen_Suit_03': { zh: '海伦摊牌', en: 'Helen Showdown' },
  'CHA_Lorelei_SSR_01': { zh: '罗蕾莱SSR', en: 'Loreley SSR' },
  'CHA_Lorelei_SSR_02': { zh: '罗蕾莱狱警', en: 'Loreley Prison Guard' },
  'CHA_Liushi_01': { zh: '刘莳', en: 'Liushih' },
  'CHA_Groza_R_01': { zh: '闪电R', en: 'Groza R' },
  'CHA_Groza_SR_01': { zh: '闪电SR', en: 'Groza SR' },
  'CHA_Groza_Rest_01': { zh: '闪电Rest', en: 'Groza Rest' },
  'CHA_Groza_Paradeus_01': { zh: '闪电Paradeus', en: 'Groza Paradeus' },
  'CHA_Groza_Mask_01': { zh: '闪电面具', en: 'Groza Mask' },
  'CHA_Charolic_SSR_01': { zh: '克罗丽科SSR', en: 'Krolik SSR' },
  'CHA_Charolic_SR_01': { zh: '克罗丽科SR', en: 'Krolik SR' },
  'CHA_Charolic_Rest_01': { zh: '克罗丽科Rest', en: 'Krolik Rest' },
  'CHA_Charolic_Paradeus_01': { zh: '克罗丽科Paradeus', en: 'Krolik Paradeus' },
  'CHA_Charolic_Mask_01': { zh: '克罗丽科面具', en: 'Krolik Mask' },
  'CHA_Dandelion_NPC_02': { zh: '丹德莱度假', en: 'Dandelion Vacation' },
  'CHA_Lenna_SSR_01': { zh: '莱娜SSR', en: 'Lenna SSR' },
  'CHA_Lenna_SSR_02': { zh: '莱娜日常装', en: 'Lenna Casual' },
  'CHA_Lenna_Suit_01': { zh: '莱娜潜入装', en: 'Lenna Disguise' },
  'CHA_Levva_NPC_01': { zh: '莱娅西装', en: 'Leva Suit' },
  'CHA_Kalina_NPC_01': { zh: '格琳娜西装', en: 'Kalina Suit' },
  'CHA_Nyto_NPC_01': { zh: '涅托', en: 'Nyto' },
  'CHA_Persicaria_NPC_01': { zh: '帕斯卡莉亚', en: 'Persica' },
  'CHA_Sexdwarf_NPC_01': { zh: '六分仪一形态', en: 'Sextans Form 1' },
  'CHA_Sexdwarf_Paradeus_01': { zh: '六分仪一形态Paradeus', en: 'Sextans Form 1 Paradeus' },
  'CHA_Tololo_SSR_01': { zh: '托洛洛SSR', en: 'Tololo SSR' },
  'CHA_Zhaohui_SSR_01': { zh: '朝晖SSR', en: 'Zhaohui SSR' },
  'CHA_Jiangyu_SSR_01': { zh: '绛雨SSR', en: 'Jiangyu SSR' },
  'CHA_Macqiato_SSR_01': { zh: '玛绮朵SSR', en: 'Makiatto SSR' },
  'CHA_Macqiato_SSR_02': { zh: '玛绮朵小熊', en: 'Makiatto Little Bear' },
  'CHA_Qiongjiu_SSR_01': { zh: '琼玖SSR', en: 'Qiongjiu SSR' },
  'CHA_Sabrina_SSR_01': { zh: '塞布丽娜SSR', en: 'Sabrina SSR' },
  'CHA_Andoris_SSR_01': { zh: '安朵丝SSR', en: 'Andoris SSR' },
  'CHA_Dusevnyj_SSR_01': { zh: '杜莎妮SSR', en: 'Dushevnaya SSR' },
  'CHA_Dusevnyj_Suit_01': { zh: '杜莎妮一代', en: 'Dushevnaya Past' },
  'CHA_Esther_NPC_01': { zh: '埃丝特', en: 'Esther' },
  'CHA_Rosaline_NPC_01': { zh: '罗莎琳', en: 'Rosalind' },
  'CHA_RegularDoll_NPC_01': { zh: '普通人形', en: 'Regular Doll' },
  'CHA_MAwomen_NPC_01': { zh: '中年女性', en: 'Middle-Aged Woman' },
  'CHA_Koshmar_NPC_01': { zh: '喀什玛', en: 'Koshmar' },
  'CHA_Clukay_SSR_01': { zh: '可露凯SSR', en: 'Klukai SSR' },
  'CHA_Vector_SSR_01': { zh: '维克托SSR', en: 'Vector SSR' },
  'CHA_Yoohee_SSR_01': { zh: '幼熙SSR', en: 'Yoohee SSR' },
  'CHA_Qiuhua_SSR_01': { zh: '秋桦SSR', en: 'Qiuhua SSR' },
  'CHA_Nikita_SSR_01': { zh: '妮基塔SSR', en: 'Nikketa SSR' },
  'CHA_Green_RichFemale01_NPC_01': { zh: '白区女性', en: 'White Zone Woman' },
  'CHA_Green_NormalFemale01_NPC_01': { zh: '绿区女性', en: 'Green Zone Woman' },
  'CHA_Yellow_NormalFemale01_NPC_01': { zh: '黄区女性', en: 'Yellow Zone Woman' },
  'CHA_Levva_SSR_01': { zh: '莱娅SSR', en: 'Leva SSR' },
  'CHA_Alf_SSR_01': { zh: '埃芙SSR', en: 'Alva SSR' },
  'CHA_Robella_SSR_01': { zh: '洛贝拉SSR', en: 'Robella SSR' },
  'CHA_Sop_NPC_01': { zh: '索普NPC', en: 'Soppo NPC' },
  'CHA_BlackGroza_NPC_01': { zh: '黑闪电', en: 'Black Groza' },
  'CHA_Lene_SSR_01': { zh: '莱妮SSR', en: 'Lainie SSR' },
  'CHA_Lene_Suit_ump40_01': { zh: '莱妮蝴蝶', en: 'Lainie Butterfly' },
  'CHA_Levva_Suit_ump45_01': { zh: '莱娅一代', en: 'Leva Past' },
  'CHA_Levva_Suit_ump45_02': { zh: '莱娅蝴蝶', en: 'Leva Butterfly' },
  'CHA_WomanA_NPC_01': { zh: '埃斯梅', en: 'Esme' },
  'CHA_Chiloveig_NPC_02': { zh: '奇洛薇格', en: 'Chiloveig' },
  'CHA_Chiloveig_NPC_01': { zh: '奇洛薇格白大褂', en: 'Chiloveig White Coat' },
  'CHA_Kalina_Suit_01': { zh: '格琳娜病服', en: 'Kalina Hospital Gown' },
  'CHA_Orpheoreon_NPC_01': { zh: '欧菲露妮研究员', en: 'Orphelune Research' },
  'CHA_Orpheoreon_NPC_02': { zh: '欧菲露妮正装', en: 'Orphelune Formal' },
  'CHA_Ange_NPC_01': { zh: '安洁莉娅', en: 'Angelia' },
  'CHA_Ange_Suit_01': { zh: '安洁莉娅武装', en: 'Angelia Armed' },
  'CHA_RPK-16_NPC_01': { zh: 'RPK-16', en: 'RPK-16' },
  'CHA_AK12_NPC_01': { zh: 'AK-12', en: 'AK-12' },
  'CHA_Beelneith_NPC_01': { zh: '贝欧尼斯', en: 'Beelneith' },
  'CHA_PersicariaDoll_NPC_01': { zh: '人形帕斯卡', en: 'Persicaria Doll' },
  'CHA_Lewis_SSR_01': { zh: '刘易斯SSR', en: 'Lewis SSR' },
  'CHA_Bereifel_NPC_01': { zh: '贝瑞菲尔', en: 'Berryfield' },
  'CHA_Phaetusa_SSR_01': { zh: '翡图萨SSR', en: 'Phaetusa SSR' },
  'CHA_Sweeper_NPC_01': { zh: '清道夫', en: 'Scavenger' },
  'CHA_manager_NPC_01': { zh: '配送站站长', en: 'Delivery Station Manager' },
  'CHA_FemaleCouriers_NPC_01': { zh: '配送员A', en: 'Deliveryman A' },
  'CHA_Sia_NPC_01': { zh: '希娅', en: 'Shea' },
  'CHA_Gaia_NPC_01': { zh: '盖娅', en: 'Gaia' },
  'CHA_Yellow_FemaleWorker_01': { zh: '黄区女工', en: 'Yellow Zone Female Worker' },
  'CHA_Basti_01': { zh: '贝丝蒂', en: 'Basti' },
  'CHA_Lydia_01': { zh: '莉迪亚', en: 'Lydia' },
  'CHA_Yellow_GuardFemale_01': { zh: '卫队成员女', en: 'Guard Member Female' },
  'CHA_Type56-1_01': { zh: '知穗NPC', en: 'Zhisui NPC' },
  'CHA_Mayling_NPC_01': { zh: '美玲', en: 'Mayling' },
  'CHA_Colphne_N_01': { zh: '寇尔芙N', en: 'Colphne N' },
  'CHA_Colphne_SR_01': { zh: '寇尔芙SR', en: 'Colphne SR' },
  'CHA_Colphne_Rest_01': { zh: '寇尔芙Rest', en: 'Colphne Rest' },
  'CHA_Colphne_Paradeus_01': { zh: '寇尔芙Paradeus', en: 'Colphne Paradeus' },
  'CHA_Darcular_NPC_01': { zh: '黑眼一形态', en: 'Darture Form 1' },
  'CHA_Helena_NPC_01': { zh: '海伦娜', en: 'Helena' },
  'CHA_Helena_Paradeus_01': { zh: '海伦娜Paradeus', en: 'Helena Paradeus' },
  'CHA_Niter_NPC_01': { zh: '妮特', en: 'Niter' },
  'CHA_Vepley_SR_01': { zh: '维普蕾SR', en: 'Vepley SR' },
  'CHA_Vepley_SSR_01': { zh: '维普蕾SSR', en: 'Vepley SSR' },
  'CHA_Vepley_Rest_01': { zh: '维普蕾Rest', en: 'Vepley Rest' },
  'CHA_Vepley_Paradeus_01': { zh: '维普蕾Paradeus', en: 'Vepley Paradeus' },
  'CHA_Nagant_SR_01': { zh: '纳甘SR', en: 'Nagant SR' },
  'CHA_Sharkry_SR_01': { zh: '夏克里SR', en: 'Sharkry SR' },
  'CHA_Sharkry_SSR_01': { zh: '夏克里SSR', en: 'Sharkry SSR' },
  'CHA_Cheeta_SR_01': { zh: '奇塔SR', en: 'Cheeta SR' },
  'CHA_Centaureissi_SSR_01': { zh: '桑朵莱希SSR', en: 'Centaureissi SSR' },
  'CHA_Ksenia_SR_01': { zh: '科谢尼娅SR', en: 'Ksenia SR' },
  'CHA_Papasha_SSR_01': { zh: '波波沙SSR', en: 'Papasha SSR' },
  'CHA_Littara_SR_01': { zh: '莉塔拉SR', en: 'Littara SR' },
  'CHA_Suomi_SSR_01': { zh: '索米SSR', en: 'Suomi SSR' },
  'CHA_Suomi_Mask_01': { zh: '索米面具', en: 'Suomi Mask' },
  'CHA_Bathilda_NPC_01': { zh: '巴希达', en: 'Bathilde' },
  'CHA_Lotta_SR_01': { zh: '洛塔SR', en: 'Lotta SR' },
  'CHA_Biyoca_SSR_01': { zh: '比悠卡SSR', en: 'Belka SSR' },
  'CHA_Mechty_SSR_01': { zh: '米什缇SSR', en: 'Mechty SSR' },
  'CHA_Suomi_Rest_01': { zh: '索米Rest', en: 'Suomi Rest' },
  'CHA_Ruchey_SSR_01': { zh: '乌琪SSR', en: 'Ruchey SSR' },
  'CHA_Harpsy_SSR_01': { zh: '哈卜茜SSR', en: 'Harpsy SSR' },
  'CHA_Welrod_SSR_01': { zh: '维尔德SSR', en: 'Welrod SSR' },
  'CHA_Aminda_NPC_01': { zh: '阿米达', en: 'Aminda' },
  'CHA_Lumi_NPC_01': { zh: '卢米', en: 'Lumi' },
  'CHA_Peri_SSR_01': { zh: '佩莉SSR', en: 'Peri SSR' },
  'CHA_Mopro1.5_NPC_01': { zh: '莫普1.5', en: 'Mopro 1.5' },
  'CHA_Faye_SSR_01': { zh: '绯SSR', en: 'Faye SSR' },
  'CHA_Helena_NPC_02': { zh: '海伦娜附体', en: 'Helena Possessed' },
  'CHA_Helena_NPC_03': { zh: '海伦娜D68', en: 'Helena D68' },
  'CHA_Green_RichBoy01_NPC_01': { zh: '白区男孩', en: 'White Zone Boy' },
  'CHA_Green_RichGirl01_NPC_01': { zh: '白区女孩', en: 'White Zone Girl' },
  'CHA_Green_NormalBoy01_NPC_01': { zh: '绿区男孩', en: 'Green Zone Boy' },
  'CHA_Green_NormalGirl01_NPC_01': { zh: '绿区女孩', en: 'Green Zone Girl' },
  'CHA_Yellow_NormalBoy01_NPC_01': { zh: '黄区男孩', en: 'Yellow Zone Boy' },
  'CHA_Yellow_NormalGirl01_NPC_01': { zh: '黄区女孩', en: 'Yellow Zone Girl' },
  'CHA_G11_Suit_MaidUniform': { zh: 'G11女仆', en: 'G11 Maid' },
  'CHA_Laibnis_NPC_01': { zh: '莱布妮丝', en: 'Leibnys' },
  'CHA_UnsearchableGirl_NPC_01': { zh: '神秘女孩', en: 'Mysterious Girl' },
  'CHA_Florence_SSR_01': { zh: '芙洛伦SSR', en: 'Florence SSR' },
  'CHA_Elnida_NPC_01': { zh: '艾琳达', en: 'Elinda' },
  'CHA_Bathilda_SSR_01': { zh: '巴希达SSR', en: 'Bathilde SSR' },
  'CHA_Orpheoreon_Kid_01': { zh: '欧菲露妮幼年', en: 'Orphelune Childhood' },
  'CHA_Heli_NPC_01': { zh: '赫利', en: 'Heli' },
  'CHA_Sakura_SSR_01': { zh: '樱花SSR', en: 'Sakura SSR' },
  'CHA_Sakura_NPC_01': { zh: '樱花快递员', en: 'Sakura Courier' },
  'CHA_Cheyanne_01': { zh: '夏安', en: 'Cheyanne' },
  'CHA_Cheyanne_02': { zh: '夏安战损', en: 'Cheyanne Damaged' },
  'CHA_Cheyanne_03': { zh: '夏安仓管', en: 'Cheyanne Warehouse' },
  'CHA_Ada_01': { zh: '佐伊', en: 'Zoe' },
  'CHA_G41_01': { zh: '芙铃', en: 'Furin' },
  'CHA_Vera_01': { zh: '薇拉', en: 'Vera' },
  'CHA_Dandelion_NPC_01': { zh: '丹德莱', en: 'Dandelion' },
  'CHA_Lene_SSR_01_OLD': { zh: '莱妮SSR（老）', en: 'Lainie SSR (outdated)' },
  'CHA_Levva_NPC_01_OLD': { zh: '莱娅西装（老）', en: 'Leva Suit (outdated)' },
  'CHA_Kalina_NPC_01_OLD': { zh: '格琳娜西装（老）', en: 'Kalina Suit (outdated)' },
};

/**
 * Utility to normalize a model id so overrides are matched reliably.
 */
export function normalizeModelId(id: string): string {
  if (!id) {
    return '';
  }
  return id.replace(/\\/g, '/');
}
